// Do not edit this file.

import { MyMigDB, Table } from "../src";
import { Datetime } from "@nence/datetime";
import { UserID } from "./id.ts";

/**
 *  Test
 */
export type TestType = {
  id?: UserID; // id
  email?: string; // email
  createdAt?: Datetime; // createdAt
};

export class TestTable
  extends Table<TestType, keyof TestType>
  implements Required<TestType>
{
  id: UserID = undefined!; // id
  email: string = undefined!; // email
  createdAt: Datetime = undefined!; // createdAt
  constructor(database: MyMigDB) {
    super("test", database);
  }
  get(): Required<TestType> {
    return {
      id: this.id,
      email: this.email,
      createdAt: this.createdAt,
    };
  }
  set(param: Required<TestType>) {
    this.id = param.id;
    this.email = param.email;
    this.createdAt = param.createdAt;
  }
}
