version: "3.9"

services:
  main:
    #image: denoland/deno:latest
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../:/usr/src/app
    ports:
      - 8000:8000
    env_file:
      - ../.env
    tty: true
    command: bash -c "/bin/bash"
  mysql:
    image: mysql:8.0.32
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - 3306:3306
    env_file:
      - ../.env
    depends_on:
      - "main"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 4040:80
    volumes:
      - ./phpmyadmin/sessions:/sessions
    env_file:
      - ../.env
    depends_on:
      - "mysql"
  # postfix:
  #   image: catatnight/postfix:latest
  #   ports:
  #     - 8025:25
  #   environment:
  #     - maildomain=mail.nekosapiens.com
  #     -
